### ISSUE TITLE
Add a simplified diagram of the SoC in the README?

### ISSUE THREAD

**Issue by enjoy-digital** [litex-hub/linux-on-litex-rocket#2]
Adding a simplified / minimal diagram of the SoC to the README would I think provide a quick and better overview of the aim of the project and what's built with it.

Here is a first attempt I just did:
![](https://user-images.githubusercontent.com/1450143/102595137-6b965680-4117-11eb-8f52-ee053a7ba31a.png)

@gsomlo: If you could be interested, happy to review / do changes to it and create a PR to the README. I also don't want to change the style of the project or transform it, so if you have preference for a full text README or wants to create your own diagram, feel to reject this.

**Comment by gsomlo** [comment]
@enjoy-digital: diagram looks great, thanks for creating it, and looking forward to the PR!

One thought: right now the DMA bus is essentially a point-to-point link between Rocket and LiteSDCard, but would you lay it out slightly differently knowing that we might one day (hopefully soon) add LiteSATA to the design, which will also need to be connected to the DMA bus? Making sure that addition will require minimal (visual) re-arrangement of the existing components might be worth a few seconds' thought :) 

Finally, not sure if we want to add IRQs to the diagram or not (probably not, but just thinking out loud).

**Comment by enjoy-digital** [comment]
@gsomlo: Thanks for the feedback, is it better like this? (rearranged the DMA + added IRQs):

![LiteX(13)](https://user-images.githubusercontent.com/1450143/102624193-f8efa000-4143-11eb-9189-a02edc161bbc.png)

Also, do you want the LiteX-Hub logo on it ? (feel free to say no, I just added it here to show you)

**Comment by gsomlo** [comment]
@enjoy-digital: looks good, thanks! Also, LiteX-Hub logo is fine with me (although, visually, I'd probably place it somewhere underneath `/dev/ttyUSBX` on the left (probably aligned with the bottom of the rest of the image) where it wouldn't have to stick out vertically. It's a minor thing, perfectly OK where it is now if "bottom-right" is sort-of a standard for logo placement...

**Comment by enjoy-digital** [comment]
PR https://github.com/litex-hub/linux-on-litex-rocket/pull/3 created with:

![](https://user-images.githubusercontent.com/1450143/102630245-9bac1c80-414c-11eb-92c9-311fd4e06bea.png)

I'll also share with you the source of this diagram.

**Comment by gsomlo** [comment]
Thanks again, looks really good. Depending on what the source looks like, we might want to make that part of the repo itself -- what do you think?

**Comment by gsomlo** [comment]
resolved by merging PR #3 -- Thanks again @enjoy-digital for putting it together!
