### ISSUE TITLE
genesys2: full4q CPU variant not supported 

### ISSUE THREAD

**Issue by newinnovations** [litex-hub/linux-on-litex-rocket#37]
Following the instructions for building for the Digilent Genesys2 ...

```sh
litex-boards/litex_boards/targets/digilent_genesys2.py --build \
    --cpu-type rocket --cpu-variant full4q --sys-clk-freq 100e6 \
    --with-ethernet --with-sdcard
```

... I get the following error:

```text
1.057 ERROR:SoC:full4q CPU variant not supported, supported are:
1.057  - full
1.057  - linux
1.057  - medium
1.057  - small
```

I am wondering whether I should use `full` or `linux` instead of `full4q`?  Or maybe I made some error installing litex.

Your help is greatly appreciated.

**Comment by gsomlo** [comment]
Have a look here: https://github.com/litex-hub/pythondata-cpu-rocket/commit/ef6cf0a11f4a5d384f72b9b3661c85ad81d5e942

The variants have been renamed so on genesys2 you should probably use `--cpu-variant linux --cpu-num-cores 4 --cpu-mem-width 4`.

The genesys2 has a 256-bit wide LiteDRAM port, hence `--cpu-mem-width 4`. You can pick the `--cpu-num-cores` you want, might be able to fit 8 of them on a large FPGA, not exactly sure (but there should be room enough for 4).

NOTE: I'd like to eliminate support for the various `--cpu-mem-width` options in the long term, but first I (or someone) would have to fix the LiteX AXI up-converter (https://github.com/enjoy-digital/litex/issues/1753 warning: the comment thread goes a bit off topic :) )

**Comment by newinnovations** [comment]
Thanks for the quick reply!
