### ISSUE TITLE
Arty A7-100T Boot Linux Panic about irqchip.

### ISSUE THREAD

**Issue by Jerryy959** [litex-hub/linux-on-litex-rocket#40]
I'm using ArtyA7-100T to boot rocketchip linux.
```
litex-boards/litex_boards/targets/digilent_arty.py --build --load \
   --cpu-type rocket --cpu-variant full --sys-clk-freq 50e6 \
   --with-ethernet --variant=a7-100
```
All works fine, but when booting the linux , i reach the followning error something about plic_irqchip:
<img width="466" alt="截屏2024-05-30 15 05 53" src="https://github.com/litex-hub/linux-on-litex-rocket/assets/48466606/cf000cf8-ce40-44f4-922f-7e511c55a819">

Things like that when claim the irq 11 , the handler->hart_base == 0, which makes the claim==0x4, leads to error.

Then i check the irpchip's probe function, as following behind, the irq_set_chained_handler doesn't return correctly, so that the code about `handler->present = true` not excute, how can i debug it ?
<img width="826" alt="截屏2024-05-30 15 09 57" src="https://github.com/litex-hub/linux-on-litex-rocket/assets/48466606/dfbf599f-3486-4d00-b191-e156029589e1">
<img width="586" alt="截屏2024-05-30 15 11 08" src="https://github.com/litex-hub/linux-on-litex-rocket/assets/48466606/b23e9298-16f8-4553-8564-c2e16e22e0c1">

**Comment by Comet959** [comment]
This problem has solved on here: https://github.com/enjoy-digital/litex/issues/1976#issue-2324919065.
it can be closed.
