### ISSUE TITLE
Running Bare Metal application code on litex with cpu type rocket

### ISSUE THREAD

**Issue by sramichetty20019** [litex-hub/linux-on-litex-rocket#42]
Hi Everyone, I am trying to run litex with Rocket as CPU type, and I am trying to demo.bin file to see if the bare metal application code execution works, i know that it doesn't work or does not produce any output while i run using the command

litex_sim --threads-8 --with-sdram --cpu-type rocket --cpu-variant small /linux --sdram-init demo.bin 

The above does not go beyond the liftoff

i also tried
litex_sim --integrated-rom-size 0x10000 --cpu-type rocket --cpu-variant small --rom-init demo.bin
this is also stuck
i want to run litex in simulation model
i have also removed the -flto flag yet it dosent work
kindly provide me some guidence to bare-metal-applications on litex simulation if possible also a way to get the instruction trace

**Comment by gsomlo** [comment]
duplicate of https://github.com/enjoy-digital/litex/issues/2010
