### ISSUE TITLE
Booting a lightweight image of linux on the litex simulator 

### ISSUE THREAD

**Issue by sramichetty20019** [litex-hub/linux-on-litex-rocket#43]
Hi everyone, i have run the Litex simulator with Linux image as directed in the repository i am using verilator based simulation, however i want to speedup the boot process and the time it takes to run commands on the bootup image. Is it possible to use any other linux distribution to do this, or else do you guys any tips for me to speed up the process , kindly let me know

**Comment by gsomlo** [comment]
A few years back, I remember booting just the kernel with a busybox based initrd in sim/verilator with rocket, and it took somewhere around 6-8 hours to complete.

Running an actual linux distro on top of sim/verilator is not likely to be a useful exercise... :)
